<a href="https://colab.research.google.com/github/WilliamsBD8/data_science_fundamentals_electiva_1/blob/main/Copia_de_numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [ ]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
print(arr)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [ ]:
arr1 = arr[3:]
print(arr1)

[5 1 2]


Using slicing print all the elements except the last one.



In [ ]:
arr2 = arr[0:-1]
print(arr2)

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [ ]:
arr3 = arr[1:5]
print(arr3)

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [ ]:
arr4 = arr.reshape(3, 2)
print(arr4)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [ ]:
for arrI in np.nditer(arr):
  print(arrI)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [ ]:
newArr = np.array([0,6,9])
print(newArr)

[0 6 9]


Join the two arrays.



In [ ]:
conArr = np.concatenate((arr, newArr))
print(conArr)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [ ]:
filterArr = conArr % 2 == 1
arrFilter = conArr[filterArr]
print(arrFilter)

[7 5 1 9]


Sort the joined array elements.



In [ ]:
arrOrder = np.sort(conArr)
print(arrOrder)

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [ ]:
month = np.array(('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'))

Split the months array in 4 periods of 3 elements each one.



In [ ]:
monthSplit = month.reshape(4, 3)
print(monthSplit)

[['Enero' 'Febrero' 'Marzo']
 ['Abril' 'Mayo' 'Junio']
 ['Julio' 'Agosto' 'Septiembre']
 ['Octubre' 'Noviembre' 'Diciembre']]


Create an array with genre information ['F','M','F','F','M','F'].



In [ ]:
genre = np.array(['F','M','F','F','M','F'])

Find the indexes where the value is F.



In [ ]:
genreFind = np.where(genre == 'F')
print(genreFind)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [ ]:
age = np.array([18,20,19,23,19,20])

Create a filter array with values < 20.



In [ ]:
filter = age < 20
ageFilter = age[filter]
print(ageFilter)

[18 19 19]


Change the 3 index element with a value of 22



In [ ]:
age[3] = 22
print(age)

[18 20 19 22 19 20]


Print the 4 index element.

In [ ]:
print(age[4])

19
